version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ckpt/backend-services
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: go build -v github.com/ckpt/backend-services
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ckpt/backend-services .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ckpt/backend-services
